const DICTIONARY = {
    en: {
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        CONFIRM: "y",
        MENU: "MENU",
        MENU_PLAY_GAME: "1. Play Game",
        MENU_SETTINGS: "2. Settings",
        MENU_EXIT: "3. Exit Game",
        MENU_TITLE: "MENU",
        INVALID_MOVE: "Invalid move. Please try again.",
        PLACE_MARK_PROMPT: "Place your mark at (row col): ",
        PLAYER: "Player {player}",
        PLAYER_TURN: "it is your turn.",
        WINNER_MESSAGE: "Winner is player {player}",
        DRAW_MESSAGE: "The game ended in a draw!",
        GAME_OVER: "GAME OVER",
        GO_BACK: "Press enter to go back to settings...",
        CHOOSE_MODE: "Choose Game Mode:",
        PVP: "1. Player vs Player",
        PVC: "2. Player vs Computer",
    },
    no: {
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        CONFIRM: "j",
        MENU: "MENY",
        MENU_PLAY_GAME: "1. Start spillet",
        MENU_SETTINGS: "2. Innstillinger",
        MENU_EXIT: "3. Avslutt spillet",
        MENU_TITLE: "MENY",
        INVALID_MOVE: "Ugyldig trekk. Prøv igjen.",
        PLACE_MARK_PROMPT: "Plasser merket ditt på (rad kolonne): ",
        PLAYER: "Spiller {player}",
        PLAYER_TURN: "det er din tur.",
        WINNER_MESSAGE: "Vinneren er spiller {player}",
        DRAW_MESSAGE: "Spillet endte uavgjort!",
        GAME_OVER: "SPILLET ER OVER",
        GO_BACK: "Trykk enter for å gå tilbake til innstillinger...",
        CHOOSE_MODE: "Velg Modus:",
        PVP: "1. Spiller mot Spiller",
        PVC: "2. Spiller mot Datamaskin",
    }
};

export default DICTIONARY;